Repository G1-Group/TheConversationsBot, pull requests merged in 2023-08, with the labels that each got.

#94 set column name zuxriddin
  TheConversationsBot/Domain/Models/AnonymChat.cs
  TheConversationsBot/Domain/Models/Board.cs
  TheConversationsBot/Domain/Models/Client.cs
  TheConversationsBot/Domain/Models/Log.cs
  TheConversationsBot/Domain/Models/Message.cs
  TheConversationsBot/Domain/Models/User.cs
  TheConversationsBot/SQLQuery/SQLQuery.sql
Labels: accepted

#95 BotClient is added
  TheConversationsBot/Program.cs
  TheConversationsBot/TelegramBot/TelegramBot.cs
Labels: accepted

#105 finished fix
  TheConversationsBot/TelegramBot/ControllerBase.cs
Labels: accepted

#104 done
  TheConversationsBot/TelegramBot/ControllerContext.cs
Labels: accepted

#106 create update handler list
  TheConversationsBot/TelegramBot/TelegramBot.cs
Labels: finished, rejected

#109 update handler
  TheConversationsBot/TelegramBot/TelegramBot.cs
Labels: finished

#110 creaded ControllerManager.cs
  TheConversationsBot/TelegramBot/ControllerBase.cs
  TheConversationsBot/TelegramBot/ControllerManager.cs
Labels: finished

#118 client service creaded
  TheConversationsBot/Service/AuthService.cs
  TheConversationsBot/Service/ClientService.cs
Labels: finished

#130 Client DBService tayyor insert qoldi faqat
  TheConversationsBot/Service/DataSource/ClientDBService.cs
  TheConversationsBot/Service/DataSource/IDBServiceBase.cs
Labels: finished

#131 anonym chat db service yaratildi
  TheConversationsBot/Domain/Models/AnonymChat.cs
  TheConversationsBot/Service/DataSource/AnonymCahtDBService.cs
  TheConversationsBot/Service/Interface/IServiceAnonymChat.cs
Labels: finished

#150 addeted DataContext
  TheConversationsBot/Service/DataContext/DataContext.cs
  TheConversationsBot/TheConversationsBot.csproj
Labels: finished

#158 Created IClientDataService and implement DataServiceBase
  TheConversationsBot/Service/DataSource/ClientDataService.cs
  TheConversationsBot/Service/DataSource/DataServiceBase.cs
  TheConversationsBot/Service/DataSource/Interfase/IClientDataService.cs
Labels: accepted

#160 Created UserDataService
  TheConversationsBot/Migrations/20230816085025_CreatedDatabase.Designer.cs
  TheConversationsBot/Migrations/DataContextModelSnapshot.cs
  TheConversationsBot/Service/DataContext/DataContext.cs
  TheConversationsBot/Service/DataSource/ClientDataService.cs
  TheConversationsBot/Service/DataSource/Interfase/IUserDataService.cs
  TheConversationsBot/Service/DataSource/UserDataService.cs
Labels: accepted

#161 159 iauthservice
  TheConversationsBot/Configurations/Settings.cs
  TheConversationsBot/Domain/Entity/Board.cs
  TheConversationsBot/Domain/Entity/Client.cs
  TheConversationsBot/Domain/Entity/Conversation.cs
  TheConversationsBot/Domain/Entity/Message.cs
  TheConversationsBot/Domain/Entity/ModelBase.cs
  TheConversationsBot/Domain/Entity/User.cs
  TheConversationsBot/Domain/Models/Session.cs
  TheConversationsBot/Domain/ViewEntity/BoardView.cs
  TheConversationsBot/Domain/ViewEntity/ConversationView.cs
  TheConversationsBot/Domain/ViewEntity/LogView.cs
  TheConversationsBot/Domain/ViewEntity/LoginView.cs
  TheConversationsBot/Domain/ViewEntity/Session.cs
  TheConversationsBot/Domain/ViewEntity/SignUpView.cs
  TheConversationsBot/Migrations/20230816114412_updateEntity.Designer.cs
  TheConversationsBot/Migrations/20230816114412_updateEntity.cs
  TheConversationsBot/Migrations/DataContextModelSnapshot.cs
  TheConversationsBot/Program.cs
  TheConversationsBot/Service/AuthService.cs
  TheConversationsBot/Service/DataContext/DataContext.cs
  TheConversationsBot/Service/Interface/IAuthService.cs
Labels: accepted

#162 Created BoardDataService
  TheConversationsBot/Service/DataSource/BoardDataService.cs
  TheConversationsBot/Service/DataSource/Interfase/IBoardDataService.cs
Labels: accepted

#177 create controller base
  TheConversationsBot/TheConversationsBot.csproj
Labels: accepted

#183 implement ControllerBase
  TheConversationsBot/TelegramBot/Controllers/ClientDashboardController.cs
  TheConversationsBot/TelegramBot/Controllers/ControllerBase.cs
  TheConversationsBot/TelegramBot/Controllers/HomeController.cs
Labels: accepted

#185 initialize manager controller
  TheConversationsBot/TelegramBot/Managers/ManagerController.cs
Labels: accepted

#184 SessionManager created
  TheConversationsBot/TelegramBot/Managers/ISessionManager.cs
  TheConversationsBot/TelegramBot/Managers/SessionManager.cs
Labels: accepted

#188 BoardController created
  TheConversationsBot/TelegramBot/Controllers/BoardController.cs
Labels: accepted

#191 created AuthController
  TheConversationsBot/TelegramBot/Controllers/AuthController.cs
  TheConversationsBot/TelegramBot/Managers/ManagerController.cs
Labels: accepted
